[package]
name = "tessellation"
version = "0.6.0"
authors = ["Henning Meyer <tutmann@gmail.com>"]

description = "3d tessellation library."
repository = "https://github.com/hmeyer/tessellation"
readme = "README.md"
keywords = ["tessellation", "3d", "manifold", "dual-contouring"]
license = "GPL-3.0"

[lib]
name = "tessellation"
path = "src/lib.rs"

[dependencies]
alga = "0.5"
nalgebra = "0.14"
rand = "0.3"
time = "0.1"
rayon = "1.0"
lazy_static = "0.2.8"
bbox = "0.8"
num-traits = "0.2"

[dev-dependencies]
approx = "0.1"
bencher = "0.1"
implicit3d = "0.9"

[[bench]]
name = "tessellation"
path = "src/benches/tessellation.rs"
harness = false
